[build-system]
# nanobind requires `typing-extensions` for stubgen on Python versions older than 3.11.
requires = ["scikit-build-core", "nanobind", "typing-extensions", "setuptools-scm"]
build-backend = "scikit_build_core.build"

[project]
name = "fastfilters2"
description = "SIMD-accelerated 2D and 3D image features"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT License" }
authors = [
    { name = "Emil Melnikov", email = "emilmelnikov@gmail.com" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "numpy>=1.21",
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/ilastik/fastfilters2"
"Bug Tracker" = "https://github.com/ilastik/fastfilters2/issues"

[tool.scikit-build]
editable.rebuild = true
build.verbose = true
build-dir = "build/{wheel_tag}"
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["python/fastfilters2/_version.py"]

[tool.setuptools_scm]
write_to = "python/fastfilters2/_version.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--quiet -ra --doctest-modules"

[tool.cibuildwheel]
build = "cp*"
skip = "*-musllinux_*"
archs = "auto64"
# In the future, cibuildwheel will switch the default backend from `pip` to `build`.
build-frontend = "build"
test-command = "pytest {package}/tests"
test-requires = "pytest"

[tool.cibuildwheel.windows]
# Use an experimental wheel repair tool on Windows (cf. `auditwheel` and `delocate`).
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos.environment]
# Minimum macOS version required for the complete C++17 support.
MACOSX_DEPLOYMENT_TARGET = "10.14"

[[tool.cibuildwheel.overrides]]
# macOS on Apple Silicon requires a higher minimum deployment target.
select = "*-macos_arm64"
environment = {MACOSX_DEPLOYMENT_TARGET = "11.0"}
