[build-system]
# nanobind requires `typing_extensions` for stubgen on Python versions older than 3.11.
requires = ["scikit-build-core", "nanobind", "typing_extensions"]
build-backend = "scikit_build_core.build"

[project]
name = "fastfilters2"
version = "2.0.0.dev1"
description = "SIMD-accelerated 2D and 3D image features"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT License" }
authors = [
    { name = "Emil Melnikov", email = "emilmelnikov@gmail.com" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "numpy>=1.21",
]

[project.urls]
"Homepage" = "https://github.com/ilastik/fastfilters2"
"Bug Tracker" = "https://github.com/ilastik/fastfilters2/issues"

[tool.scikit-build]
editable.rebuild = true
build.verbose = true
build-dir = "build/{wheel_tag}"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--quiet -ra --doctest-modules"

[tool.cibuildwheel]
skip = "pp*"
archs = ["auto64"]
test-requires = ["pytest"]
test-command = "pytest"

# Minimum macOS version required for the complete C++17 support.
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"
